name: MLOps Pipeline

on: [push]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11 to match your local version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug - Print working directory
        run: pwd

      - name: Debug - List files
        run: ls -l

      - name: Train model
        run: python train.py

      - name: Debug - Verify model file exists
        run: |
          if [ -f "iris_model.pkl" ]; then
            echo "Model file (iris_model.pkl) exists."
          else
            echo "Model file (iris_model.pkl) does not exist."
            exit 1
          fi

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: iris_model.pkl